<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-9FJDGC5" name="Default test" tests="2" failures="1" timestamp="15 Dec 2017 14:20:57 GMT" time="90.054" errors="0">
  <testcase name="userLogin" time="60.971" classname="com.trackx.truelocate.flow.IMIdentifierTypeAdvFilter"/>
  <testcase name="itemClassCreateFlow" time="0.0" classname="com.trackx.truelocate.flow.IMIdentifierTypeAdvFilter">
    <failure type="org.testng.TestNGException" message="
The data provider is trying to pass 4 parameters but the method com.trackx.truelocate.flow.IMIdentifierTypeAdvFilter#itemClassCreateFlow takes 5 and TestNG is unable in inject a suitable object">
      <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 4 parameters but the method com.trackx.truelocate.flow.IMIdentifierTypeAdvFilter#itemClassCreateFlow takes 5 and TestNG is unable in inject a suitable object
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1361)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1225)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1359)
	... 17 more
]]>
    </failure>
  </testcase> <!-- itemClassCreateFlow -->
</testsuite> <!-- Default test -->
